from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import Select
driver=webdriver.Chrome(executable_path="C:\\Users\\admin\\chromedriver_win32\\chromedriver.exe")
driver.get("https://itera-qa.azurewebsites.net/home/automation")
fname=driver.find_element(By.ID,"name")
fname.send_keys("nanda kishore")
mobile=driver.find_element(By.ID,"phone")
mobile.send_keys("9868960086")
mail=driver.find_element(By.ID,"email")
mail.send_keys("nandak551@gmail.com")
pwrd=driver.find_element(By.ID,"password")
pwrd.send_keys("ncjebc")
add=driver.find_element(By.ID,"address")
add.send_keys("hyderabad")
button=driver.find_element_by_name("submit")
button.click()
radiobutton=driver.find_element_by_id("female").click()
radiobutton=driver.find_element_by_id("female").is_selected()
print(radiobutton)
driver.find_element_by_id("monday").click()
driver.find_element_by_id("sunday").click()
ele=driver.find_element_by_xpath("body/div[1]/div[4]/div[2]/div[1]/select[1]")
drp=Select(ele)
drp.deselect_by_visible_index("2")
